### PR TITLE
Remove default indent

### PR DESCRIPTION
**Pull request by mohd-akram**

### CODE REVIEW

**Review by Dezzj — APPROVED** [review]
Approved

**Comment by Lewiscowles1986** [comment]
Surely this is a breaking change?

**Comment by doowb** [comment]
@Lewiscowles1986 thanks for catching this. This PR was merged into master over 5 years ago and I didn't notice that it wasn't published to NPM.

I'll get a new patch released that reverts this PR.

**Comment by Lewiscowles1986** [comment]
😬 what about just releasing a major, or I contribute some docs about the breakage for a 1.2.5?

My comment wasn't meant to do more than ignite discussion; I was not trying to tell what you should do; but I did get an update notification for this on a repo, and I read the changelog, and was curious.

I was kinda hoping you'd tell me I read it wrong 😂

**Comment by doowb** [comment]
> I was kinda hoping you'd tell me I read it wrong

@Lewiscowles1986 you read it correctly and you're right that it's a breaking change. Since 1.2.4 is intentionally a patch to fix #32 , the default indent change should be in a new version. I get annoyed by patches having breaking changes, so I'm glad you caught that.

I see you created a PR to re-add this change. Thanks for doing that and I'll try to get it merged and published soon.

**Pull request merged**
